apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gatsby-docker-de
  namespace: '847897790789'
  selfLink: /apis/serving.knative.dev/v1/namespaces/847897790789/services/gatsby-docker-de
  uid: 60643da1-8455-44a2-aabf-ace4356493b4
  resourceVersion: AAXMp7HJ5O8
  generation: 5
  creationTimestamp: '2021-08-01T21:19:29.371113Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: ad38fca8-d74c-4983-959e-7eb7e8a58ad9
    commit-sha: 63b269f114fa15917a6d7cf61a573e122e14c178
    gcb-build-id: 0d750cf2-2643-4b0e-a329-0a5a9f1da3dc
    cloud.googleapis.com/location: us-west1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: peteburquette@gmail.com
    serving.knative.dev/lastModifier: 847897790789@cloudbuild.gserviceaccount.com
    client.knative.dev/user-image: us.gcr.io/reactdockerde2/gatsby-react-de/gatsby-docker-de:63b269f114fa15917a6d7cf61a573e122e14c178
    run.googleapis.com/client-version: 358.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: gatsby-docker-de-00005-wer
      labels:
        managed-by: gcp-cloud-build-deploy-cloud-run
        gcb-trigger-id: ad38fca8-d74c-4983-959e-7eb7e8a58ad9
        commit-sha: 63b269f114fa15917a6d7cf61a573e122e14c178
        gcb-build-id: 0d750cf2-2643-4b0e-a329-0a5a9f1da3dc
      annotations:
        run.googleapis.com/client-name: gcloud
        client.knative.dev/user-image: us.gcr.io/reactdockerde2/gatsby-react-de/gatsby-docker-de:63b269f114fa15917a6d7cf61a573e122e14c178
        run.googleapis.com/client-version: 358.0.0
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 847897790789-compute@developer.gserviceaccount.com
      containers:
      - image: us.gcr.io/reactdockerde2/gatsby-react-de/gatsby-docker-de:63b269f114fa15917a6d7cf61a573e122e14c178
        ports:
        - name: http1
          containerPort: 443
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 5
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2021-09-23T11:11:37.956591Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2021-09-23T11:11:32.376710Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2021-09-23T11:11:37.956591Z'
  latestReadyRevisionName: gatsby-docker-de-00005-wer
  latestCreatedRevisionName: gatsby-docker-de-00005-wer
  traffic:
  - revisionName: gatsby-docker-de-00005-wer
    percent: 100
    latestRevision: true
  url: https://gatsby-docker-de-mki3ctcl2a-uw.a.run.app
  address:
    url: https://gatsby-docker-de-mki3ctcl2a-uw.a.run.app
